using System.Collections.Generic;
using SQLite;

namespace TelehackHelper.Core.Entities
{
    public class AreaCode
    {
        [PrimaryKey, AutoIncrement]
        public int Id { get; set; }
        [NotNull]
        public string State { get; set; }
        [Unique, NotNull]
        public int Code { get; set; }

        public static List<AreaCode> AreaCodes = new List<AreaCode>()
        {
            new AreaCode { State = "Alberta", Code = 403 },
            new AreaCode { State = "Alaska", Code = 907 },
            new AreaCode { State = "Alabama", Code = 205 },
            new AreaCode { State = "Alabama", Code = 334 },
            new AreaCode { State = "Alabama", Code = 256 },
            new AreaCode { State = "Arkansas", Code = 501 },
            new AreaCode { State = "Arizona", Code = 602 },
            new AreaCode { State = "Arizona", Code = 520 },
            new AreaCode { State = "British Columbia", Code = 604 },
            new AreaCode { State = "British Columbia", Code = 250 },
            new AreaCode { State = "California", Code = 415 },
            new AreaCode { State = "California", Code = 408 },
            new AreaCode { State = "California", Code = 619 },
            new AreaCode { State = "California", Code = 714 },
            new AreaCode { State = "California", Code = 805 },
            new AreaCode { State = "California", Code = 818 },
            new AreaCode { State = "California", Code = 916 },
            new AreaCode { State = "California", Code = 310 },
            new AreaCode { State = "California", Code = 213 },
            new AreaCode { State = "California", Code = 510 },
            new AreaCode { State = "California", Code = 209 },
            new AreaCode { State = "California", Code = 707 },
            new AreaCode { State = "California", Code = 562 },
            new AreaCode { State = "California", Code = 323 },
            new AreaCode { State = "California", Code = 858 },
            new AreaCode { State = "California", Code = 909 },
            new AreaCode { State = "Colorado", Code = 303 },
            new AreaCode { State = "Colorado", Code = 719 },
            new AreaCode { State = "Connecticut", Code = 203 },
            new AreaCode { State = "District of Columbia", Code = 202 },
            new AreaCode { State = "Delaware", Code = 302 },
            new AreaCode { State = "Dominican Republic", Code = 809 },
            new AreaCode { State = "Florida", Code = 407 },
            new AreaCode { State = "Florida", Code = 305 },
            new AreaCode { State = "Florida", Code = 904 },
            new AreaCode { State = "Florida", Code = 813 },
            new AreaCode { State = "Florida", Code = 321 },
            new AreaCode { State = "Florida", Code = 386 },
            new AreaCode { State = "Georgia", Code = 404 },
            new AreaCode { State = "Georgia", Code = 912 },
            new AreaCode { State = "Georgia", Code = 706 },
            new AreaCode { State = "Georgia", Code = 478 },
            new AreaCode { State = "Guam", Code = 671 },
            new AreaCode { State = "Hawaii", Code = 808 },
            new AreaCode { State = "Iowa", Code = 319 },
            new AreaCode { State = "Iowa", Code = 515 },
            new AreaCode { State = "Iowa", Code = 712 },
            new AreaCode { State = "Iowa", Code = 641 },
            new AreaCode { State = "Idaho", Code = 208 },
            new AreaCode { State = "Illinois", Code = 312 },
            new AreaCode { State = "Illinois", Code = 708 },
            new AreaCode { State = "Illinois", Code = 309 },
            new AreaCode { State = "Illinois", Code = 217 },
            new AreaCode { State = "Illinois", Code = 815 },
            new AreaCode { State = "Illinois", Code = 618 },
            new AreaCode { State = "Indiana", Code = 317 },
            new AreaCode { State = "Indiana", Code = 219 },
            new AreaCode { State = "Indiana", Code = 812 },
            new AreaCode { State = "Kansas", Code = 913 },
            new AreaCode { State = "Kansas", Code = 316 },
            new AreaCode { State = "Kentucky", Code = 502 },
            new AreaCode { State = "Kentucky", Code = 606 },
            new AreaCode { State = "Louisiana", Code = 504 },
            new AreaCode { State = "Louisiana", Code = 318 },
            new AreaCode { State = "Louisiana", Code = 337 },
            new AreaCode { State = "Massachusetts", Code = 617 },
            new AreaCode { State = "Massachusetts", Code = 508 },
            new AreaCode { State = "Massachusetts", Code = 413 },
            new AreaCode { State = "Massachusetts", Code = 339 },
            new AreaCode { State = "Massachusetts", Code = 351 },
            new AreaCode { State = "Midway Islands", Code = 301 },
            new AreaCode { State = "Midway Islands", Code = 410 },
            new AreaCode { State = "Maine", Code = 207 },
            new AreaCode { State = "Michigan", Code = 313 },
            new AreaCode { State = "Michigan", Code = 616 },
            new AreaCode { State = "Michigan", Code = 517 },
            new AreaCode { State = "Michigan", Code = 906 },
            new AreaCode { State = "Michigan", Code = 248 },
            new AreaCode { State = "Minnesota", Code = 612 },
            new AreaCode { State = "Minnesota", Code = 218 },
            new AreaCode { State = "Minnesota", Code = 507 },
            new AreaCode { State = "Missouri", Code = 314 },
            new AreaCode { State = "Missouri", Code = 816 },
            new AreaCode { State = "Missouri", Code = 417 },
            new AreaCode { State = "Mississippi", Code = 601 },
            new AreaCode { State = "Montana", Code = 406 },
            new AreaCode { State = "North Carolina", Code = 919 },
            new AreaCode { State = "North Carolina", Code = 704 },
            new AreaCode { State = "North Carolina", Code = 336 },
            new AreaCode { State = "North Dakota", Code = 701 },
            new AreaCode { State = "Nebraska", Code = 402 },
            new AreaCode { State = "Nebraska", Code = 308 },
            new AreaCode { State = "New Hampshire", Code = 603 },
            new AreaCode { State = "New Jersey", Code = 201 },
            new AreaCode { State = "New Jersey", Code = 609 },
            new AreaCode { State = "New Jersey", Code = 908 },
            new AreaCode { State = "New Jersey", Code = 551 },
            new AreaCode { State = "New Jersey", Code = 732 },
            new AreaCode { State = "New Mexico", Code = 505 },
            new AreaCode { State = "Nova Scotia", Code = 902 },
            new AreaCode { State = "Nevada", Code = 702 },
            new AreaCode { State = "New York", Code = 212 },
            new AreaCode { State = "New York", Code = 914 },
            new AreaCode { State = "New York", Code = 716 },
            new AreaCode { State = "New York", Code = 516 },
            new AreaCode { State = "New York", Code = 315 },
            new AreaCode { State = "New York", Code = 718 },
            new AreaCode { State = "New York", Code = 518 },
            new AreaCode { State = "New York", Code = 607 },
            new AreaCode { State = "Ohio", Code = 216 },
            new AreaCode { State = "Ohio", Code = 513 },
            new AreaCode { State = "Ohio", Code = 614 },
            new AreaCode { State = "Ohio", Code = 419 },
            new AreaCode { State = "Oklahoma", Code = 405 },
            new AreaCode { State = "Oklahoma", Code = 918 },
            new AreaCode { State = "Oklahoma", Code = 580 },
            new AreaCode { State = "Ontario", Code = 416 },
            new AreaCode { State = "Ontario", Code = 519 },
            new AreaCode { State = "Ontario", Code = 613 },
            new AreaCode { State = "Ontario", Code = 705 },
            new AreaCode { State = "Ontario", Code = 807 },
            new AreaCode { State = "Oregon", Code = 503 },
            new AreaCode { State = "Oregon", Code = 541 },
            new AreaCode { State = "Pennsylvania", Code = 215 },
            new AreaCode { State = "Pennsylvania", Code = 717 },
            new AreaCode { State = "Pennsylvania", Code = 412 },
            new AreaCode { State = "Pennsylvania", Code = 814 },
            new AreaCode { State = "Pennsylvania", Code = 610 },
            new AreaCode { State = "Rhode Island", Code = 401 },
            new AreaCode { State = "South Carolina", Code = 803 },
            new AreaCode { State = "South Dakota", Code = 605 },
            new AreaCode { State = "Saskatchewan", Code = 306 },
            new AreaCode { State = "Tennessee", Code = 615 },
            new AreaCode { State = "Tennessee", Code = 901 },
            new AreaCode { State = "Tennessee", Code = 931 },
            new AreaCode { State = "Texas", Code = 512 },
            new AreaCode { State = "Texas", Code = 713 },
            new AreaCode { State = "Texas", Code = 214 },
            new AreaCode { State = "Texas", Code = 817 },
            new AreaCode { State = "Texas", Code = 915 },
            new AreaCode { State = "Texas", Code = 409 },
            new AreaCode { State = "Texas", Code = 806 },
            new AreaCode { State = "Texas", Code = 903 },
            new AreaCode { State = "Texas", Code = 210 },
            new AreaCode { State = "Texas", Code = 972 },
            new AreaCode { State = "Texas", Code = 325 },
            new AreaCode { State = "Texas", Code = 432 },
            new AreaCode { State = "Utah", Code = 801 },
            new AreaCode { State = "Virginia", Code = 703 },
            new AreaCode { State = "Virginia", Code = 804 },
            new AreaCode { State = "Virginia", Code = 540 },
            new AreaCode { State = "Virginia", Code = 571 },
            new AreaCode { State = "Vermont", Code = 802 },
            new AreaCode { State = "Washington", Code = 206 },
            new AreaCode { State = "Washington", Code = 509 },
            new AreaCode { State = "Washington", Code = 360 },
            new AreaCode { State = "Wisconsin", Code = 414 },
            new AreaCode { State = "Wisconsin", Code = 608 },
            new AreaCode { State = "Wisconsin", Code = 715 },
            new AreaCode { State = "West Virginia", Code = 304 },
            new AreaCode { State = "Wyoming", Code = 307 }
        };
    }
}
